# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b92012151a9fb60d749864f7446ee6daf6c100cbd6cf9f1774afc03a1d015842ca8c6be900b5060862019ed0013489a3f09e72e9282a36c9afeaaf19651bd0a

  amazon_access_key: <%= ENV['AMAZON_ACCESS_KEY'] %>
  amazon_secret_key: <%= ENV['AMAZON_SECRET_KEY'] %>

test:
  secret_key_base: b14666fd9194f69bd460b6d095731377cdbb9afc4722aeccd7b6eacadeb12f5fcc46a0a3f942ce981664c5caa19aeb85b01ef5e71ed3a0f1ca8d1161b288b7f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

  amazon_access_key: <%= ENV['AMAZON_ACCESS_KEY'] %>
  amazon_secret_key: <%= ENV['AMAZON_SECRET_KEY'] %>

  rds_database: <%= ENV['RDS_DB_NAME'] %>
  rds_username: <%= ENV['RDS_USERNAME'] %>
  rds_password: <%= ENV['RDS_PASSWORD'] %>
  rds_host: <%= ENV['RDS_HOST'] %>
  rds_port: <%= ENV['RDS_PORT'] %>